# Generated by Django 3.2 on 2021-04-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('framac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='directory',
            new_name='parent_directory',
        ),
        migrations.AddField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framac.directory'),
        ),
        migrations.AddField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
