# Generated by Django 3.2 on 2021-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framac', '0002_auto_20210426_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
